name: discglowing
version: "${version}"
main: com.spectrasonic.discglowing.Main
api-version: "1.21"
authors: [Spectrasonic]
commands:
    discglowing:
        aliases: [dg]
        permission: discglowing.admin
permissions:
    discglowing.admin:
        default: op
